[package]
name = "roesti"
version = "0.1.0"
edition = "2021"

[dependencies]
dynamic_services = "0.1.1"
once_cell = "1.20"
uuid = { version = "1", features = ["v4"]}

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
codegen-units = 1
strip = true
